language: node_js
    - "7"
install: 
    - npm install 
services: 
    - postgresql 
cache: 
    directories: 
        - "node_modules"
script: npm run test:api
before_script:
    - psql -c "CREATE DATABASE eventsmanager_test;" -U postgres
after_script: 
    - nyc report --reporter=text-lcov | coveralls
    # - codeclimate-test-reporter < ./coverage/lcov.info
    # - coveralls < ./coverage/lcov.info
